package edu.rpi.tw.rds.vocabulary;

import com.hp.hpl.jena.ontology.*;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Resource;

/**
 * @author szednik
 * Auto-generated by schemagen on 15 Aug 2014, edited by szednik
 */
public class DCAT {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM, null);

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/ns/dcat#";

    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );

    /** <p>Could  be any kind of URL that gives access to a distribution of the dataset.
     *  E.g. landing page, download, feed URL, SPARQL endpoint. Use when your catalog does
     *  not have information on which it is or when it is definitely not a download.</p>
     */
    public static final ObjectProperty accessURL = m_model.createObjectProperty( "http://www.w3.org/ns/dcat#accessURL" );

    /** <p>Links a dataset to relevant contact information which is provided using VCard.</p>
     */
    public static final ObjectProperty contactPoint = m_model.createObjectProperty( "http://www.w3.org/ns/dcat#contactPoint" );

    /** <p>Links a catalog to a dataset that is part of the catalog.</p>
     */
    public static final ObjectProperty dataset = m_model.createObjectProperty( "http://www.w3.org/ns/dcat#dataset" );

    /** <p>Connects a dataset to its available distributions.</p>
     */
    public static final ObjectProperty distribution = m_model.createObjectProperty( "http://www.w3.org/ns/dcat#distribution" );

    /** <p>This is a direct link to a downloadable file in a given format.
     *  E.g. CSV file or RDF file. The format is described by the distribution's
     *  dc:format and/or dcat:mediaType</p>
     */
    public static final ObjectProperty downloadURL = m_model.createObjectProperty( "http://www.w3.org/ns/dcat#downloadURL" );

    /** <p>A Web page that can be navigated to in a Web browser to gain access to
     *  the dataset, its distributions and/or additional information.</p>
     */
    public static final ObjectProperty landingPage = m_model.createObjectProperty( "http://www.w3.org/ns/dcat#landingPage" );

    /** <p>This property SHOULD be used when the media type of the distribution is
     *  defined in IANA, otherwise dct:format MAY be used with different values.</p>
     */
    public static final ObjectProperty mediaType = m_model.createObjectProperty( "http://www.w3.org/ns/dcat#mediaType" );

    /** <p>Links a catalog to its records.</p>
     */
    public static final ObjectProperty record = m_model.createObjectProperty( "http://www.w3.org/ns/dcat#record" );

    /** <p>The main category of the dataset. A dataset can have multiple themes.</p>
     */
    public static final ObjectProperty theme = m_model.createObjectProperty( "http://www.w3.org/ns/dcat#theme" );

    /** <p>The knowledge organization system (KOS) used to classify catalog's datasets.</p>
     */
    public static final ObjectProperty themeTaxonomy = m_model.createObjectProperty( "http://www.w3.org/ns/dcat#themeTaxonomy" );

    /** <p>The size of a distribution in bytes.</p>
     */
    public static final DatatypeProperty byteSize = m_model.createDatatypeProperty( "http://www.w3.org/ns/dcat#byteSize" );

    /** <p>describe size of resource in bytes. This term has been deprecated</p> */
    @Deprecated
    public static final DatatypeProperty bytes = m_model.createDatatypeProperty( "http://www.w3.org/ns/dcat#bytes" );

    /** <p>A keyword or tag describing the dataset.</p>
     */
    public static final DatatypeProperty keyword = m_model.createDatatypeProperty( "http://www.w3.org/ns/dcat#keyword" );

    /** <p>links a dataset to a dictionary that helps interpreting the data. This term
     *  has been deprecated</p>
     */
    @Deprecated
    public static final OntProperty dataDictionary = m_model.createOntProperty( "http://www.w3.org/ns/dcat#dataDictionary" );

    /** <p>describes the quality of data e.g. precision. This should not be used to describe
     *  the data collection characteristics, other more specialized statistical properties
     *  can be used instead. This term has been deprecated</p>
     */
    @Deprecated
    public static final OntProperty dataQuality = m_model.createOntProperty( "http://www.w3.org/ns/dcat#dataQuality" );

    /** <p>describes the level of granularity of data in a dataset. The granularity can
     *  be in time, place etc. This term has been deprecated</p>
     */
    @Deprecated
    public static final OntProperty granularity = m_model.createOntProperty( "http://www.w3.org/ns/dcat#granularity" );

    /** <p>the size of a distribution. This term has been deprecated</p> */
    @Deprecated
    public static final OntProperty size = m_model.createOntProperty( "http://www.w3.org/ns/dcat#size" );

    /** <p>A curated collection of metadata about datasets</p>
     */
    public static final OntClass Catalog = m_model.createClass( "http://www.w3.org/ns/dcat#Catalog" );

    /** <p>A record in a data catalog, describing a single dataset</p>
     */
    public static final OntClass CatalogRecord = m_model.createClass( "http://www.w3.org/ns/dcat#CatalogRecord" );

    /** <p>A collection of data, published or curated by a single source, and available
     *  for access or download in one or more formats</p>
     */
    public static final OntClass Dataset = m_model.createClass( "http://www.w3.org/ns/dcat#Dataset" );

    /** <p>Represents a specific available form of a dataset. Each dataset might be
     *  available in different forms, these forms might represent different formats
     *  of the dataset or different endpoints. Examples of distributions include a
     *  downloadable CSV file, an API or an RSS feed</p>
     */
    public static final OntClass Distribution = m_model.createClass( "http://www.w3.org/ns/dcat#Distribution" );

    /** <p>represents a downloadable distribution of a dataset. This term has been deprecated</p> */
    @Deprecated
    public static final OntClass Download = m_model.createClass( "http://www.w3.org/ns/dcat#Download" );

    /** <p>represents availability of a dataset as a feed. This term has been deprecated</p> */
    @Deprecated
    public static final OntClass Feed = m_model.createClass( "http://www.w3.org/ns/dcat#Feed" );

    /** <p>represents a web service that enables access to the data of a dataset. This
     *  term has been deprecated</p>
     */
    @Deprecated
    public static final OntClass WebService = m_model.createClass( "http://www.w3.org/ns/dcat#WebService" );

}
