package edu.rpi.tw.rds.vocabulary;

import com.hp.hpl.jena.ontology.*;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from /Users/szednik/Projects/RDS/DatasetRegistrationService/src/main/resources/rdf/vivo-isf-public-1.6.owl
 * @author Auto-generated by schemagen on 15 Aug 2014 00:30
 */
public class VIVO {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM, null);

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://vivoweb.org/ontology/core#";

    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );

    public static final ObjectProperty affiliatedOrganization = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#affiliatedOrganization" );

    public static final ObjectProperty assignedBy = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#assignedBy" );

    public static final ObjectProperty assignee = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#assignee" );

    public static final ObjectProperty assigneeFor = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#assigneeFor" );

    public static final ObjectProperty assigns = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#assigns" );

    public static final ObjectProperty contributingRole = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#contributingRole" );

    public static final ObjectProperty dateFiled = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#dateFiled" );

    public static final ObjectProperty dateIssued = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#dateIssued" );

    public static final ObjectProperty dateTime = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#dateTime" );

    public static final ObjectProperty dateTimeInterval = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#dateTimeInterval" );

    public static final ObjectProperty dateTimePrecision = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#dateTimePrecision" );

    public static final ObjectProperty dateTimeValue = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#dateTimeValue" );

    public static final ObjectProperty degreeCandidacy = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#degreeCandidacy" );

    public static final ObjectProperty distributes = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#distributes" );

    public static final ObjectProperty distributesFundingFrom = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#distributesFundingFrom" );

    public static final ObjectProperty eligibleFor = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#eligibleFor" );

    public static final ObjectProperty end = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#end" );

    public static final ObjectProperty equipmentFor = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#equipmentFor" );

    public static final ObjectProperty expirationDate = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#expirationDate" );

    public static final ObjectProperty facilityFor = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#facilityFor" );

    public static final ObjectProperty featuredIn = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#featuredIn" );

    public static final ObjectProperty features = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#features" );

    public static final ObjectProperty fundingVehicleFor = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#fundingVehicleFor" );

    public static final ObjectProperty geographicFocus = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#geographicFocus" );

    public static final ObjectProperty geographicFocusOf = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#geographicFocusOf" );

    public static final ObjectProperty governingAuthorityFor = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#governingAuthorityFor" );

    public static final ObjectProperty grantSubcontractedThrough = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#grantSubcontractedThrough" );

    public static final ObjectProperty hasAssociatedConcept = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#hasAssociatedConcept" );

    public static final ObjectProperty hasCollaborator = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#hasCollaborator" );

    public static final ObjectProperty hasEquipment = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#hasEquipment" );

    public static final ObjectProperty hasPredecessorOrganization = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#hasPredecessorOrganization" );

    public static final ObjectProperty hasPrerequisite = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#hasPrerequisite" );

    public static final ObjectProperty hasProceedings = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#hasProceedings" );

    public static final ObjectProperty hasPublicationVenue = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#hasPublicationVenue" );

    public static final ObjectProperty hasResearchArea = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#hasResearchArea" );

    public static final ObjectProperty hasSubjectArea = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#hasSubjectArea" );

    public static final ObjectProperty hasSuccessorOrganization = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#hasSuccessorOrganization" );

    public static final ObjectProperty hasTranslation = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#hasTranslation" );

    public static final ObjectProperty informationResourceSupportedBy = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#informationResourceSupportedBy" );

    public static final ObjectProperty offeredBy = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#offeredBy" );

    public static final ObjectProperty offers = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#offers" );

    public static final ObjectProperty orcidId = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#orcidId" );

    public static final ObjectProperty prerequisiteFor = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#prerequisiteFor" );

    public static final ObjectProperty proceedingsOf = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#proceedingsOf" );

    public static final ObjectProperty providesFundingThrough = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#providesFundingThrough" );

    public static final ObjectProperty publicationVenueFor = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#publicationVenueFor" );

    public static final ObjectProperty publisher = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#publisher" );

    public static final ObjectProperty publisherOf = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#publisherOf" );

    public static final ObjectProperty relatedBy = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#relatedBy" );

    public static final ObjectProperty relates = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#relates" );

    public static final ObjectProperty reproduces = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#reproduces" );

    public static final ObjectProperty researchAreaOf = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#researchAreaOf" );

    public static final ObjectProperty reviewedIn = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#reviewedIn" );

    public static final ObjectProperty roleContributesTo = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#roleContributesTo" );

    public static final ObjectProperty sponsoredBy = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#sponsoredBy" );

    public static final ObjectProperty sponsors = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#sponsors" );

    public static final ObjectProperty start = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#start" );

    public static final ObjectProperty subcontractsGrant = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#subcontractsGrant" );

    public static final ObjectProperty subjectAreaOf = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#subjectAreaOf" );

    public static final ObjectProperty supportedBy = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#supportedBy" );

    public static final ObjectProperty supportedInformationResource = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#supportedInformationResource" );

    public static final ObjectProperty supports = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#supports" );

    public static final ObjectProperty translatorOf = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#translatorOf" );

    public static final ObjectProperty validIn = m_model.createObjectProperty( "http://vivoweb.org/ontology/core#validIn" );

    public static final DatatypeProperty abbreviation = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#abbreviation" );

    public static final DatatypeProperty cclCode = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#cclCode" );

    public static final DatatypeProperty courseCredits = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#courseCredits" );

    public static final DatatypeProperty departmentOrSchool = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#departmentOrSchool" );

    public static final DatatypeProperty description = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#description" );

    public static final DatatypeProperty eRACommonsId = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#eRACommonsId" );

    public static final DatatypeProperty entryTerm = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#entryTerm" );

    public static final DatatypeProperty freetextKeyword = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#freetextKeyword" );

    public static final DatatypeProperty grantDirectCosts = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#grantDirectCosts" );

    public static final DatatypeProperty hasMonetaryAmount = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#hasMonetaryAmount" );

    public static final DatatypeProperty hasValue = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#hasValue" );

    public static final DatatypeProperty hideFromDisplay = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#hideFromDisplay" );

    public static final DatatypeProperty hrJobTitle = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#hrJobTitle" );

    public static final DatatypeProperty iclCode = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#iclCode" );

    public static final DatatypeProperty identifier = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#identifier" );

    public static final DatatypeProperty isCorrespondingAuthor = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#isCorrespondingAuthor" );

    public static final DatatypeProperty licenseNumber = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#licenseNumber" );

    public static final DatatypeProperty localAwardId = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#localAwardId" );

    public static final DatatypeProperty majorField = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#majorField" );

    public static final DatatypeProperty middleName = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#middleName" );

    public static final DatatypeProperty nihmsid = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#nihmsid" );

    public static final DatatypeProperty outreachOverview = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#outreachOverview" );

    public static final DatatypeProperty overview = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#overview" );

    public static final DatatypeProperty patentNumber = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#patentNumber" );

    public static final DatatypeProperty placeOfPublication = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#placeOfPublication" );

    public static final DatatypeProperty pmcid = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#pmcid" );

    public static final DatatypeProperty preferredDisplayOrder = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#preferredDisplayOrder" );

    public static final DatatypeProperty rank = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#rank" );

    public static final DatatypeProperty reportId = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#reportId" );

    public static final DatatypeProperty researchOverview = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#researchOverview" );

    public static final DatatypeProperty researcherId = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#researcherId" );

    public static final DatatypeProperty scopusId = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#scopusId" );

    public static final DatatypeProperty seatingCapacity = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#seatingCapacity" );

    public static final DatatypeProperty sponsorAwardId = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#sponsorAwardId" );

    public static final DatatypeProperty supplementalInformation = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#supplementalInformation" );

    public static final DatatypeProperty teachingOverview = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#teachingOverview" );

    public static final DatatypeProperty termLabel = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#termLabel" );

    public static final DatatypeProperty termType = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#termType" );

    public static final DatatypeProperty totalAwardAmount = m_model.createDatatypeProperty( "http://vivoweb.org/ontology/core#totalAwardAmount" );

    public static final OntClass Abstract = m_model.createClass( "http://vivoweb.org/ontology/core#Abstract" );

    public static final OntClass AcademicDegree = m_model.createClass( "http://vivoweb.org/ontology/core#AcademicDegree" );

    public static final OntClass AcademicDepartment = m_model.createClass( "http://vivoweb.org/ontology/core#AcademicDepartment" );

    public static final OntClass AcademicTerm = m_model.createClass( "http://vivoweb.org/ontology/core#AcademicTerm" );

    public static final OntClass AcademicYear = m_model.createClass( "http://vivoweb.org/ontology/core#AcademicYear" );

    public static final OntClass AdministratorRole = m_model.createClass( "http://vivoweb.org/ontology/core#AdministratorRole" );

    public static final OntClass AdviseeRole = m_model.createClass( "http://vivoweb.org/ontology/core#AdviseeRole" );

    public static final OntClass AdvisingProcess = m_model.createClass( "http://vivoweb.org/ontology/core#AdvisingProcess" );

    public static final OntClass AdvisingRelationship = m_model.createClass( "http://vivoweb.org/ontology/core#AdvisingRelationship" );

    public static final OntClass AdvisorRole = m_model.createClass( "http://vivoweb.org/ontology/core#AdvisorRole" );

    public static final OntClass Association = m_model.createClass( "http://vivoweb.org/ontology/core#Association" );

    public static final OntClass AttendeeRole = m_model.createClass( "http://vivoweb.org/ontology/core#AttendeeRole" );

    public static final OntClass AttendingProcess = m_model.createClass( "http://vivoweb.org/ontology/core#AttendingProcess" );

    /** <p></p> */
    public static final OntClass Authorship = m_model.createClass( "http://vivoweb.org/ontology/core#Authorship" );

    public static final OntClass Award = m_model.createClass( "http://vivoweb.org/ontology/core#Award" );

    public static final OntClass AwardReceipt = m_model.createClass( "http://vivoweb.org/ontology/core#AwardReceipt" );

    public static final OntClass AwardedDegree = m_model.createClass( "http://vivoweb.org/ontology/core#AwardedDegree" );

    public static final OntClass Blog = m_model.createClass( "http://vivoweb.org/ontology/core#Blog" );

    public static final OntClass BlogPosting = m_model.createClass( "http://vivoweb.org/ontology/core#BlogPosting" );

    public static final OntClass Building = m_model.createClass( "http://vivoweb.org/ontology/core#Building" );

    public static final OntClass Campus = m_model.createClass( "http://vivoweb.org/ontology/core#Campus" );

    public static final OntClass CaseStudy = m_model.createClass( "http://vivoweb.org/ontology/core#CaseStudy" );

    public static final OntClass Catalog = m_model.createClass( "http://vivoweb.org/ontology/core#Catalog" );

    public static final OntClass Center = m_model.createClass( "http://vivoweb.org/ontology/core#Center" );

    public static final OntClass Certificate = m_model.createClass( "http://vivoweb.org/ontology/core#Certificate" );

    public static final OntClass Certification = m_model.createClass( "http://vivoweb.org/ontology/core#Certification" );

    public static final OntClass ClinicalOrganization = m_model.createClass( "http://vivoweb.org/ontology/core#ClinicalOrganization" );

    public static final OntClass ClinicalRole = m_model.createClass( "http://vivoweb.org/ontology/core#ClinicalRole" );

    public static final OntClass CoPrincipalInvestigatorRole = m_model.createClass( "http://vivoweb.org/ontology/core#CoPrincipalInvestigatorRole" );

    public static final OntClass College = m_model.createClass( "http://vivoweb.org/ontology/core#College" );

    public static final OntClass Committee = m_model.createClass( "http://vivoweb.org/ontology/core#Committee" );

    public static final OntClass Company = m_model.createClass( "http://vivoweb.org/ontology/core#Company" );

    public static final OntClass Competition = m_model.createClass( "http://vivoweb.org/ontology/core#Competition" );

    public static final OntClass ConferencePaper = m_model.createClass( "http://vivoweb.org/ontology/core#ConferencePaper" );

    public static final OntClass ConferencePoster = m_model.createClass( "http://vivoweb.org/ontology/core#ConferencePoster" );

    public static final OntClass ConferenceSeries = m_model.createClass( "http://vivoweb.org/ontology/core#ConferenceSeries" );

    public static final OntClass Consortium = m_model.createClass( "http://vivoweb.org/ontology/core#Consortium" );

    public static final OntClass Continent = m_model.createClass( "http://vivoweb.org/ontology/core#Continent" );

    public static final OntClass Contract = m_model.createClass( "http://vivoweb.org/ontology/core#Contract" );

    public static final OntClass CoreLaboratory = m_model.createClass( "http://vivoweb.org/ontology/core#CoreLaboratory" );

    public static final OntClass Country = m_model.createClass( "http://vivoweb.org/ontology/core#Country" );

    public static final OntClass County = m_model.createClass( "http://vivoweb.org/ontology/core#County" );

    public static final OntClass Course = m_model.createClass( "http://vivoweb.org/ontology/core#Course" );

    public static final OntClass Credential = m_model.createClass( "http://vivoweb.org/ontology/core#Credential" );

    public static final OntClass Database = m_model.createClass( "http://vivoweb.org/ontology/core#Database" );

    public static final OntClass Dataset = m_model.createClass( "http://vivoweb.org/ontology/core#Dataset" );

    public static final OntClass DateTimeInterval = m_model.createClass( "http://vivoweb.org/ontology/core#DateTimeInterval" );

    public static final OntClass DateTimeValue = m_model.createClass( "http://vivoweb.org/ontology/core#DateTimeValue" );

    public static final OntClass DateTimeValuePrecision = m_model.createClass( "http://vivoweb.org/ontology/core#DateTimeValuePrecision" );

    public static final OntClass Department = m_model.createClass( "http://vivoweb.org/ontology/core#Department" );

    public static final OntClass Division = m_model.createClass( "http://vivoweb.org/ontology/core#Division" );

    public static final OntClass EditorRole = m_model.createClass( "http://vivoweb.org/ontology/core#EditorRole" );

    public static final OntClass EditorialArticle = m_model.createClass( "http://vivoweb.org/ontology/core#EditorialArticle" );

    public static final OntClass Editorship = m_model.createClass( "http://vivoweb.org/ontology/core#Editorship" );

    public static final OntClass EducationalProcess = m_model.createClass( "http://vivoweb.org/ontology/core#EducationalProcess" );

    public static final OntClass EmeritusFaculty = m_model.createClass( "http://vivoweb.org/ontology/core#EmeritusFaculty" );

    public static final OntClass EmeritusLibrarian = m_model.createClass( "http://vivoweb.org/ontology/core#EmeritusLibrarian" );

    public static final OntClass EmeritusProfessor = m_model.createClass( "http://vivoweb.org/ontology/core#EmeritusProfessor" );

    public static final OntClass Equipment = m_model.createClass( "http://vivoweb.org/ontology/core#Equipment" );

    public static final OntClass EventSeries = m_model.createClass( "http://vivoweb.org/ontology/core#EventSeries" );

    public static final OntClass Exhibit = m_model.createClass( "http://vivoweb.org/ontology/core#Exhibit" );

    public static final OntClass ExtensionUnit = m_model.createClass( "http://vivoweb.org/ontology/core#ExtensionUnit" );

    public static final OntClass F1000Link = m_model.createClass( "http://vivoweb.org/ontology/core#F1000Link" );

    public static final OntClass Facility = m_model.createClass( "http://vivoweb.org/ontology/core#Facility" );

    public static final OntClass FacultyAdministrativePosition = m_model.createClass( "http://vivoweb.org/ontology/core#FacultyAdministrativePosition" );

    public static final OntClass FacultyMember = m_model.createClass( "http://vivoweb.org/ontology/core#FacultyMember" );

    public static final OntClass FacultyMentoringRelationship = m_model.createClass( "http://vivoweb.org/ontology/core#FacultyMentoringRelationship" );

    public static final OntClass FacultyPosition = m_model.createClass( "http://vivoweb.org/ontology/core#FacultyPosition" );

    public static final OntClass Foundation = m_model.createClass( "http://vivoweb.org/ontology/core#Foundation" );

    public static final OntClass FundingOrganization = m_model.createClass( "http://vivoweb.org/ontology/core#FundingOrganization" );

    public static final OntClass GeographicLocation = m_model.createClass( "http://vivoweb.org/ontology/core#GeographicLocation" );

    public static final OntClass GeographicRegion = m_model.createClass( "http://vivoweb.org/ontology/core#GeographicRegion" );

    public static final OntClass GeopoliticalEntity = m_model.createClass( "http://vivoweb.org/ontology/core#GeopoliticalEntity" );

    public static final OntClass GovernmentAgency = m_model.createClass( "http://vivoweb.org/ontology/core#GovernmentAgency" );

    public static final OntClass GraduateAdvisingRelationship = m_model.createClass( "http://vivoweb.org/ontology/core#GraduateAdvisingRelationship" );

    public static final OntClass GraduateStudent = m_model.createClass( "http://vivoweb.org/ontology/core#GraduateStudent" );

    public static final OntClass Grant = m_model.createClass( "http://vivoweb.org/ontology/core#Grant" );

    public static final OntClass Hospital = m_model.createClass( "http://vivoweb.org/ontology/core#Hospital" );

    public static final OntClass Institute = m_model.createClass( "http://vivoweb.org/ontology/core#Institute" );

    public static final OntClass Internship = m_model.createClass( "http://vivoweb.org/ontology/core#Internship" );

    public static final OntClass InvestigatorRole = m_model.createClass( "http://vivoweb.org/ontology/core#InvestigatorRole" );

    public static final OntClass InvitedTalk = m_model.createClass( "http://vivoweb.org/ontology/core#InvitedTalk" );

    public static final OntClass IssuedCredential = m_model.createClass( "http://vivoweb.org/ontology/core#IssuedCredential" );

    public static final OntClass Laboratory = m_model.createClass( "http://vivoweb.org/ontology/core#Laboratory" );

    public static final OntClass LeaderRole = m_model.createClass( "http://vivoweb.org/ontology/core#LeaderRole" );

    public static final OntClass Librarian = m_model.createClass( "http://vivoweb.org/ontology/core#Librarian" );

    public static final OntClass LibrarianPosition = m_model.createClass( "http://vivoweb.org/ontology/core#LibrarianPosition" );

    public static final OntClass Library = m_model.createClass( "http://vivoweb.org/ontology/core#Library" );

    public static final OntClass License = m_model.createClass( "http://vivoweb.org/ontology/core#License" );

    public static final OntClass Licensure = m_model.createClass( "http://vivoweb.org/ontology/core#Licensure" );

    public static final OntClass Location = m_model.createClass( "http://vivoweb.org/ontology/core#Location" );

    public static final OntClass MedicalResidency = m_model.createClass( "http://vivoweb.org/ontology/core#MedicalResidency" );

    public static final OntClass Meeting = m_model.createClass( "http://vivoweb.org/ontology/core#Meeting" );

    public static final OntClass MemberRole = m_model.createClass( "http://vivoweb.org/ontology/core#MemberRole" );

    public static final OntClass Museum = m_model.createClass( "http://vivoweb.org/ontology/core#Museum" );

    public static final OntClass NewsRelease = m_model.createClass( "http://vivoweb.org/ontology/core#NewsRelease" );

    public static final OntClass Newsletter = m_model.createClass( "http://vivoweb.org/ontology/core#Newsletter" );

    public static final OntClass NonAcademic = m_model.createClass( "http://vivoweb.org/ontology/core#NonAcademic" );

    public static final OntClass NonAcademicPosition = m_model.createClass( "http://vivoweb.org/ontology/core#NonAcademicPosition" );

    public static final OntClass NonFacultyAcademic = m_model.createClass( "http://vivoweb.org/ontology/core#NonFacultyAcademic" );

    public static final OntClass NonFacultyAcademicPosition = m_model.createClass( "http://vivoweb.org/ontology/core#NonFacultyAcademicPosition" );

    public static final OntClass OrganizerRole = m_model.createClass( "http://vivoweb.org/ontology/core#OrganizerRole" );

    public static final OntClass OrganizingProcess = m_model.createClass( "http://vivoweb.org/ontology/core#OrganizingProcess" );

    public static final OntClass OutreachProviderRole = m_model.createClass( "http://vivoweb.org/ontology/core#OutreachProviderRole" );

    public static final OntClass PeerReviewerRole = m_model.createClass( "http://vivoweb.org/ontology/core#PeerReviewerRole" );

    public static final OntClass PopulatedPlace = m_model.createClass( "http://vivoweb.org/ontology/core#PopulatedPlace" );

    public static final OntClass Position = m_model.createClass( "http://vivoweb.org/ontology/core#Position" );

    public static final OntClass Postdoc = m_model.createClass( "http://vivoweb.org/ontology/core#Postdoc" );

    public static final OntClass PostdocOrFellowAdvisingRelationship = m_model.createClass( "http://vivoweb.org/ontology/core#PostdocOrFellowAdvisingRelationship" );

    public static final OntClass PostdocPosition = m_model.createClass( "http://vivoweb.org/ontology/core#PostdocPosition" );

    public static final OntClass PostdoctoralTraining = m_model.createClass( "http://vivoweb.org/ontology/core#PostdoctoralTraining" );

    public static final OntClass Presentation = m_model.createClass( "http://vivoweb.org/ontology/core#Presentation" );

    public static final OntClass PresenterRole = m_model.createClass( "http://vivoweb.org/ontology/core#PresenterRole" );

    public static final OntClass PresentingProcess = m_model.createClass( "http://vivoweb.org/ontology/core#PresentingProcess" );

    public static final OntClass PrimaryPosition = m_model.createClass( "http://vivoweb.org/ontology/core#PrimaryPosition" );

    public static final OntClass PrincipalInvestigatorRole = m_model.createClass( "http://vivoweb.org/ontology/core#PrincipalInvestigatorRole" );

    public static final OntClass PrivateCompany = m_model.createClass( "http://vivoweb.org/ontology/core#PrivateCompany" );

    public static final OntClass Program = m_model.createClass( "http://vivoweb.org/ontology/core#Program" );

    public static final OntClass Project = m_model.createClass( "http://vivoweb.org/ontology/core#Project" );

    public static final OntClass Publisher = m_model.createClass( "http://vivoweb.org/ontology/core#Publisher" );

    public static final OntClass Relationship = m_model.createClass( "http://vivoweb.org/ontology/core#Relationship" );

    public static final OntClass ResearchOrganization = m_model.createClass( "http://vivoweb.org/ontology/core#ResearchOrganization" );

    public static final OntClass ResearchProposal = m_model.createClass( "http://vivoweb.org/ontology/core#ResearchProposal" );

    public static final OntClass ResearcherRole = m_model.createClass( "http://vivoweb.org/ontology/core#ResearcherRole" );

    public static final OntClass Review = m_model.createClass( "http://vivoweb.org/ontology/core#Review" );

    public static final OntClass ReviewerRole = m_model.createClass( "http://vivoweb.org/ontology/core#ReviewerRole" );

    public static final OntClass Room = m_model.createClass( "http://vivoweb.org/ontology/core#Room" );

    public static final OntClass School = m_model.createClass( "http://vivoweb.org/ontology/core#School" );

    public static final OntClass Score = m_model.createClass( "http://vivoweb.org/ontology/core#Score" );

    public static final OntClass Screenplay = m_model.createClass( "http://vivoweb.org/ontology/core#Screenplay" );

    public static final OntClass SeminarSeries = m_model.createClass( "http://vivoweb.org/ontology/core#SeminarSeries" );

    public static final OntClass ServiceProvidingLaboratory = m_model.createClass( "http://vivoweb.org/ontology/core#ServiceProvidingLaboratory" );

    public static final OntClass Speech = m_model.createClass( "http://vivoweb.org/ontology/core#Speech" );

    public static final OntClass StateOrProvince = m_model.createClass( "http://vivoweb.org/ontology/core#StateOrProvince" );

    public static final OntClass Student = m_model.createClass( "http://vivoweb.org/ontology/core#Student" );

    public static final OntClass StudentOrganization = m_model.createClass( "http://vivoweb.org/ontology/core#StudentOrganization" );

    /** <p>For example, the Midwest, northeast U.S.</p> */
    public static final OntClass SubnationalRegion = m_model.createClass( "http://vivoweb.org/ontology/core#SubnationalRegion" );

    public static final OntClass TeacherRole = m_model.createClass( "http://vivoweb.org/ontology/core#TeacherRole" );

    public static final OntClass Team = m_model.createClass( "http://vivoweb.org/ontology/core#Team" );

    public static final OntClass Translation = m_model.createClass( "http://vivoweb.org/ontology/core#Translation" );

    public static final OntClass UndergraduateAdvisingRelationship = m_model.createClass( "http://vivoweb.org/ontology/core#UndergraduateAdvisingRelationship" );

    public static final OntClass UndergraduateStudent = m_model.createClass( "http://vivoweb.org/ontology/core#UndergraduateStudent" );

    public static final OntClass University = m_model.createClass( "http://vivoweb.org/ontology/core#University" );

    public static final OntClass Video = m_model.createClass( "http://vivoweb.org/ontology/core#Video" );

    public static final OntClass WorkingPaper = m_model.createClass( "http://vivoweb.org/ontology/core#WorkingPaper" );

    public static final OntClass WorkshopSeries = m_model.createClass( "http://vivoweb.org/ontology/core#WorkshopSeries" );

    public static final Individual inPress = m_model.createIndividual( "http://vivoweb.org/ontology/core#inPress", m_model.createClass( "http://www.w3.org/2002/07/owl#NamedIndividual" ) );

    public static final Individual invited = m_model.createIndividual( "http://vivoweb.org/ontology/core#invited", m_model.createClass( "http://www.w3.org/2002/07/owl#NamedIndividual" ) );

    public static final Individual submitted = m_model.createIndividual( "http://vivoweb.org/ontology/core#submitted", m_model.createClass( "http://www.w3.org/2002/07/owl#NamedIndividual" ) );

    public static final Individual yearMonthDayPrecision = m_model.createIndividual( "http://vivoweb.org/ontology/core#yearMonthDayPrecision", m_model.createClass( "http://www.w3.org/2002/07/owl#NamedIndividual" ) );

    public static final Individual yearMonthDayTimePrecision = m_model.createIndividual( "http://vivoweb.org/ontology/core#yearMonthDayTimePrecision", m_model.createClass( "http://www.w3.org/2002/07/owl#NamedIndividual" ) );

    public static final Individual yearMonthPrecision = m_model.createIndividual( "http://vivoweb.org/ontology/core#yearMonthPrecision", m_model.createClass( "http://www.w3.org/2002/07/owl#NamedIndividual" ) );

    public static final Individual yearPrecision = m_model.createIndividual( "http://vivoweb.org/ontology/core#yearPrecision", m_model.createClass( "http://www.w3.org/2002/07/owl#NamedIndividual" ) );

}
